### ISSUE TITLE
Checklist 0.4.0 - Turn tail.writer into an real Markup Editor

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/tail.writer#3]
I'm currently working on Version 0.4.0 (The first Beta version), which turns the tail.writer script from a GFMarkdown editor into an universal Markup Editor. This version will already support BBCode and Textile, more Markup languages are available in future releases!

The current process:

- [x] New Factory / AMD Layout with jQuery and MooTools bindings
- [x] A new Markup API
- [x] A new String / Translation API
- [x] A new `classNames` option, which replaces `classes` and allows different arguments
- [x] A new event listeners / A custom event binding function called `on()`
- [x] A new keyCode-Listener / A new keyCode binding function called `bind()` (incl. SHIFT, CTRL, ALT)
- [x] A new `config()` method to get / set options during the runtime.
- [x] Updated tail helper methods
- [x] The Markdown Actions has been moved to an own file
- [x] The `indent` and `outdent` options are "global" actions and can be used on any markup.
- [x] The `toolbar` option allows also a callback function (SHOULD return an toolbar array).
- [x] The `statusbar` option allows also a callback function (to create an own statusbar).
- [x] The `tooltip` option allows also a callback function (to create own tooltips)
- [x] The new `reload()` method, which `remove()` and `init()` the tail.writer instance.
- [x] The new global `fullscreen` action
- [x] All required icons for the BBCode / Textile Markup
- [x] A general "popup" / "overlay" method which replaces "dropdown" / "dialog" / "tooltip"
- [x] Some additional Markup action configurations to allow a deeper control / customization
- [x] A scrollable / multiline toolbar for small devices.
- [x] Some many code improvements / design changes
- [x] The BBCode Markup 
- [x] The Textile Markup
- [ ] Exit a Walker Markup by pressing the button again [#4]
- [x] **Bugfix** The `animate()` helper method supports now IE >= 9
- [x] **Bugfix** A beter constructor-instance checl.
- [x] **Bugfix** The instance -> attribute string doesn't match..
- [x] **Bugfix** The `position` property has been assigned with the value `position` (invalid) on the cloned element within the `resize()` method!
- [x] Bugfix: Start (following / new) ordered Lists at 1. (check empty Lines between 2 ordered lists) [#4]
- [x] Bugfix: Ordered Lists aren't walkable anymore after the second item [#4]

Undecided
-----------
The following functions MAY appear in this release too

- [ ] The Key-Binding for `TAB` to switch from TableCell to TableCell (within a table only!)
- [ ] Prevent LineBreak on Enter inside an inline action, by repeating the markup.
- [ ] Color Picker
- [ ] FontFamily Picker
- [ ] FontSize Picker

**Comment by SamBrishes** [comment]
t

# Icons List

## Inline Actions
- [ ]   Acronym
- [x]   Bold
- [ ]   Big
- [ ]   Citation
- [x]   Code [Inline]
- [ ]   eMail Link
- [ ]   Font Family
- [x]   Link
- [x]   Image
- [x]   Italic
- [ ]   Small
- [ ]   Span
- [x]   Strikethrough
- [ ]   Subscript
- [ ]   Superscript
- [ ]   Text Color
- [ ]   Text Size
- [x]   Underline

## Block Actions
- [x]   Blockquote
- [x]   Code [Block]
- [ ]   Definition List
- [x]   Horizontal Rule
- [x]   Header [1 - 6]
- [x]   Header [Dropdown]
- [x]   List [Ordered]
- [x]   List [Unordered]
- [x]   List [Checked]
- [x]   List [Unchecked]
- [ ]   Paragraph [Left]
- [ ]   Paragraph [Right]
- [ ]   Paragraph [Center]
- [ ]   Paragraph [Justify]
- [ ]   Pre-Formatted Text
- [x]   Table

## Special Actions
- [x]   Indent
- [x]   Oudent
- [x]   Preview
- [x]   Editor (End Preview)
- [x]   Fullscreen (Maximize)
- [x]   Fullscreen (Minimize)
- [x]   Help
